#!/bin/sh
exec < /dev/tty

while true; do
  read -p "Do you want to run drush cex? (Y/n) " yn
  if [ "$yn" = "" ]; then
    yn='Y'
  fi
  case $yn in
      [Yy] )
        cd web;
        DRUSH_OUTPUT=$(drush cex --quiet --yes);
        cd ..;
        git add config;
        break;;
      [Nn] )
        exit;;
      * )
        echo "Please answer y or n for yes or no.";;
  esac
done
